AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  Template for lambda
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # I don't know what this is
    Timeout: 30
    Layers:
      - !Ref DepLayer

Resources:
  ScrapeFunction:
    Type: AWS::Serverless::Function
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: 'src/'
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      FunctionName: webScrapersProd
      Environment:
        Parameters:
          SUMO_LOG_LEVEL:
            Type: String
          SUMO_MAX_RETRY:
            Type: String
          SUMO_HTTP_ENDPOINT:
            Type: String
      # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      # Events:
      Policies:
        - AmazonDynamoDBFullAccess
  DepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: scraper-dependencies
      Description: Dependencies for scraper
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete

Parameters:
  SUMO_LOG_LEVEL:
    Type: String
  SUMO_MAX_RETRY:
    Type: String
  SUMO_HTTP_ENDPOINT:
    Type: String
