name: deploy to lambda

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - run: pip install -r requirements.txt --target=dependencies/python
    - run: echo ${{ secrets.DISCORD_SCRAPER_LOG_WEBHOOK }} >> ./src/utils/.discord-webhook
    - run: echo ${{ secrets.SUMO_CODE }} >> ./src/utils/.sumo-code
    - run: echo ${{ secrets.GEOCOD_IO_KEY }} >> ./src/utils/.geocod-io-key

    - uses: aws-actions/setup-sam@v1
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        aws-region: 'us-east-1'

    # Build using SAM
    - run: |
        sam build --use-container --template-file template.yml
    # Deploy on AWS
    - run: sam deploy --no-fail-on-empty-changeset

    # - name: Package Zip
    #   run: cd ./src; zip -r ../webScrapersProd.zip ./*; cd ..;
    # - name: AWS Lambda Deploy
    #   uses: appleboy/lambda-action@master
    #   with:
    #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws_region: us-east-1
    #     function_name: webScrapersProd
    #     zip_file: webScrapersProd.zip
    #     dry_run: false
