name: Lint & Test

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.9', '3.10' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install ".[tests]"

      # As pre-commit does not support user installs, we set
      # PIP_USER=0 to not do a user install.
      - name: Run pre-commit hooks
        run: export PIP_USER=0; pre-commit run --all-files

      - name: Run tests
        run: pytest
