---
name: Deploy the lambda
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt --target=dependencies/python
      - run: echo ${{ secrets.DISCORD_SCRAPER_LOG_WEBHOOK }} >> ./src/utils/.discord-webhook
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: 'us-east-1'
      # Build using SAM
      - run: |
          sam build --use-container --template-file template.yml \
          --parameter-overrides ParameterKey=SUMO_LOG_LEVEL,ParameterValue=info ParameterKey=SUMO_MAX_RETRY,ParameterValue=3 ParameterKey=SUMO_HTTP_ENDPOINT,ParameterValue=${{ secrets.SUMO_HTTP_ENDPOINT }}
      # Deploy on AWS
      - run: sam deploy --no-fail-on-empty-changeset
